import type { SearchProduct } from './types';

const sharedEggKeywords = ['달걀', '계란', '유정란'];

export const productSearchMocks: SearchProduct[] = [
  {
    id: 'search-egg-1',
    detailProductId: 'free-range-eggs',
    imageUrl: '/images/search/egg-1.png',
    name: '완전방사 무항생제 유정란',
    price: 6700,
    unit: '(10구)',
    shippingLabel: '4만원 이상 무료배송',
    isAvailable: true,
    searchKeywords: sharedEggKeywords,
  },
  {
    id: 'search-egg-2',
    imageUrl: '/images/search/egg-2.png',
    name: '황금빛 구운 유정란 10구',
    price: 6440,
    unit: '(10구)',
    shippingLabel: '4만원 이상 무료배송',
    isAvailable: true,
    searchKeywords: sharedEggKeywords,
  },
  {
    id: 'search-egg-3',
    imageUrl: '/images/search/egg-3.png',
    name: 'NONGMO 동물복지 유정란(난각번호2번)',
    price: 6210,
    unit: '(10구)',
    shippingLabel: '4만원 이상 무료배송',
    isAvailable: true,
    searchKeywords: sharedEggKeywords,
  },
  {
    id: 'search-egg-4',
    imageUrl: '/images/search/egg-4.png',
    name: '[백봉오골계] 자유방목 유정란 10구',
    price: 11900,
    unit: '(10구)',
    shippingLabel: '4만원 이상 무료배송',
    isAvailable: true,
    searchKeywords: sharedEggKeywords,
  },
  {
    id: 'search-egg-5',
    imageUrl: '/images/search/egg-5.png',
    name: '동물복지 유정 반숙란 10구',
    price: 6950,
    unit: '(10구)',
    shippingLabel: '4만원 이상 무료배송',
    isAvailable: true,
    searchKeywords: sharedEggKeywords,
  },
  {
    id: 'search-egg-6',
    imageUrl: '/images/search/egg-6.png',
    name: '[국민란] 촉촉 부드러운 간이 배어있는 반숙란 반숙 계란 삶은계란 30구',
    price: 20900,
    unit: '(30구)',
    shippingLabel: '4만원 이상 무료배송',
    isAvailable: false,
    searchKeywords: sharedEggKeywords,
  },
  {
    id: 'search-egg-7',
    imageUrl: '/images/search/egg-7.png',
    name: '30구*2판. 무항생제 동물복지유정란(60구)',
    price: 25000,
    unit: '(60구)',
    shippingLabel: '4만원 이상 무료배송',
    isAvailable: false,
    searchKeywords: sharedEggKeywords,
  },
  {
    id: 'search-egg-8',
    imageUrl: '/images/search/egg-8.png',
    name: '오메가3 동물복지 유정란(20구)',
    price: 11000,
    unit: '(20구)',
    shippingLabel: '4만원 이상 무료배송',
    isAvailable: false,
    searchKeywords: sharedEggKeywords,
  },
];
