/** 목업 화면과 테스트에서 사용할 팬트리 식재료 데이터 제공함 */

import type { PantryItem } from './types';

export const pantryItems: PantryItem[] = [
  {
    id: 'sugar',
    name: '설탕',
    daysUntilExpiration: 122,
    expirationLabel: '소비기한 122일 남음',
    expirationStatus: 'NORMAL',
    consumptionDate: '2027-01-14',
    availability: 'AVAILABLE',
    imageAlt: '설탕',
    imageUrl: '/images/pantry/sugar.png',
    storageType: 'ROOM_TEMP',
    registrationSource: 'PURCHASED',
    createdAt: '2026-09-10T10:00:00Z',
  },
  {
    id: 'green-onion',
    name: '대파',
    daysUntilExpiration: 14,
    expirationLabel: '소비기한 14일 남음',
    expirationStatus: 'NORMAL',
    consumptionDate: '2026-09-28',
    availability: 'AVAILABLE',
    imageAlt: '대파',
    imageUrl: '/images/pantry/green-onion.png',
    storageType: 'REFRIGERATED',
    registrationSource: 'PURCHASED',
    createdAt: '2026-09-10T09:00:00Z',
  },
  {
    id: 'tomato',
    name: '토마토',
    daysUntilExpiration: 5,
    expirationLabel: '소비기한 5일 남음',
    expirationStatus: 'NORMAL',
    consumptionDate: '2026-09-19',
    availability: 'AVAILABLE',
    imageAlt: '토마토',
    imageUrl: '/images/pantry/tomato.png',
    storageType: 'REFRIGERATED',
    registrationSource: 'PURCHASED',
    createdAt: '2026-09-10T08:00:00Z',
  },
  {
    id: 'olive-oil',
    name: '올리브유',
    daysUntilExpiration: 30,
    expirationLabel: '소비기한 30일 남음',
    expirationStatus: 'NORMAL',
    consumptionDate: '2026-10-14',
    availability: 'AVAILABLE',
    imageAlt: '올리브유',
    imageUrl: '/images/pantry/olive-oil.png',
    storageType: 'ROOM_TEMP',
    registrationSource: 'MANUAL',
    createdAt: '2026-09-10T07:00:00Z',
  },
  {
    id: 'dumpling',
    name: '만두',
    daysUntilExpiration: 10,
    expirationLabel: '소비기한 10일 남음',
    expirationStatus: 'NORMAL',
    consumptionDate: '2026-09-24',
    availability: 'AVAILABLE',
    imageAlt: '만두',
    imageUrl: '/images/pantry/dumpling.png',
    storageType: 'FROZEN',
    registrationSource: 'MANUAL',
    createdAt: '2026-09-10T06:00:00Z',
  },
  {
    id: 'pork',
    name: '돼지고기',
    daysUntilExpiration: 4,
    expirationLabel: '소비기한 4일 남음',
    expirationStatus: 'NORMAL',
    consumptionDate: '2026-09-18',
    availability: 'AVAILABLE',
    imageAlt: '돼지고기',
    imageUrl: '/images/pantry/pork.png',
    storageType: 'FROZEN',
    registrationSource: 'MANUAL',
    createdAt: '2026-09-10T05:00:00Z',
  },
  {
    id: 'banana',
    name: '바나나',
    daysUntilExpiration: 2,
    expirationLabel: '소비기한 2일 남음',
    expirationStatus: 'IMMINENT',
    consumptionDate: '2026-09-16',
    availability: 'AVAILABLE',
    imageAlt: '바나나',
    imageUrl: '/images/pantry/banana.png',
    storageType: 'ROOM_TEMP',
    registrationSource: 'MANUAL',
    createdAt: '2026-09-10T04:00:00Z',
  },
  {
    id: 'lettuce',
    name: '양상추',
    daysUntilExpiration: -1,
    expirationLabel: '소비기한 경과',
    expirationStatus: 'EXPIRED',
    consumptionDate: '2026-09-13',
    availability: 'AVAILABLE',
    imageAlt: '양상추',
    imageUrl: '/images/pantry/lettuce.png',
    storageType: 'REFRIGERATED',
    registrationSource: 'MANUAL',
    createdAt: '2026-09-10T03:00:00Z',
  },
  {
    id: 'bread',
    name: '식빵',
    daysUntilExpiration: -2,
    expirationLabel: '소비기한 경과',
    expirationStatus: 'EXPIRED',
    consumptionDate: '2026-09-12',
    availability: 'AVAILABLE',
    imageAlt: '식빵',
    imageUrl: '/images/pantry/bread.png',
    storageType: 'ROOM_TEMP',
    registrationSource: 'MANUAL',
    createdAt: '2026-09-10T02:00:00Z',
  },
  {
    id: 'leaf-lettuce',
    name: '상추',
    daysUntilExpiration: -3,
    expirationLabel: '소비기한 경과',
    expirationStatus: 'EXPIRED',
    consumptionDate: '2026-09-11',
    availability: 'AVAILABLE',
    imageAlt: '상추',
    imageUrl: '/images/pantry/leaf-lettuce.png',
    storageType: 'REFRIGERATED',
    registrationSource: 'MANUAL',
    createdAt: '2026-09-10T01:00:00Z',
  },
];
